# Generated by Django 3.2.13 on 2022-04-14 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='баланс'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='num_card',
            field=models.CharField(blank=True, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Карта содержит не 16 цифр или не платежной системы Мир', regex='^2200\\d{12}$')], verbose_name='номер карта жителя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Не допустимый формат', regex='^\\+?1?\\d{8,15}$')], verbose_name='телефон'),
        ),
    ]
