# Generated by Django 3.2.13 on 2022-04-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_auto_20220414_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_organization',
            field=models.BooleanField(default=False, verbose_name='организация'),
        ),
    ]
