# Generated by Django 3.2.13 on 2022-04-18 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_loyalty', '0012_auto_20220418_1756'),
        ('app_user', '0004_customuser_is_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app_loyalty.organization', verbose_name='организация'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_organization',
            field=models.BooleanField(default=False, verbose_name='представитель организации'),
        ),
    ]
