# Generated by Django 3.2.13 on 2022-04-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0007_alter_customuser_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='num_card',
            field=models.CharField(blank=True, max_length=16, verbose_name='номер карты жителя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=16, verbose_name='телефон'),
        ),
    ]
