# Generated by Django 3.2.13 on 2022-04-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0009_auto_20220419_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='perm',
            field=models.CharField(blank=True, choices=[('может_списать', 'может_списать'), ('может_начислять', 'может_начислять')], max_length=50, verbose_name='права'),
        ),
    ]
