# Generated by Django 3.2.13 on 2022-04-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0010_customuser_perm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='perm',
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_accrue',
            field=models.BooleanField(default=False, verbose_name='может начислять'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_deduct',
            field=models.BooleanField(default=False, verbose_name='может списывать'),
        ),
    ]
