# Generated by Django 3.2.13 on 2022-04-19 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_loyalty', '0012_auto_20220418_1756'),
        ('app_user', '0011_auto_20220419_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_up', models.DateField(auto_now_add=True, verbose_name='дата')),
                ('type', models.CharField(choices=[('Списано', 'Списано'), ('Начислено', 'Начислено')], max_length=100, verbose_name='тип операции')),
                ('sum_points', models.PositiveIntegerField(verbose_name='количество баллов')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app_loyalty.organization', verbose_name='организация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'история',
                'verbose_name_plural': 'истории',
                'db_table': 'history',
                'ordering': ['-created_up'],
            },
        ),
    ]
