# Generated by Django 3.2.13 on 2022-04-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='заголовок')),
                ('description', models.TextField(verbose_name='содержание')),
                ('created_up', models.DateField(auto_now_add=True, verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('inn', models.PositiveIntegerField(verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'организации',
                'db_table': 'organizations',
            },
        ),
    ]
