# Generated by Django 3.2.13 on 2022-04-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_loyalty', '0002_auto_20220415_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='изображение'),
        ),
    ]
