# Generated by Django 3.2.13 on 2022-04-15 12:16

import app_loyalty.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_loyalty', '0003_organization_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='img',
        ),
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, upload_to=app_loyalty.models.news_img_directory_path, verbose_name='изображение'),
        ),
    ]
