# Generated by Django 3.2.13 on 2022-04-18 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_loyalty', '0004_auto_20220415_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_descr',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='краткое содержание'),
            preserve_default=False,
        ),
    ]
