# Generated by Django 3.2.13 on 2022-04-18 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_loyalty', '0005_news_short_descr'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.EmailField(blank=True, max_length=254, verbose_name='сайт организации'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='описание')),
                ('start_date', models.DateField(verbose_name='дата начала')),
                ('finish_date', models.DateField(verbose_name='дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_loyalty.organization', verbose_name='организация')),
            ],
            options={
                'verbose_name': 'скидка',
                'verbose_name_plural': 'скидки',
                'db_table': 'discounts',
            },
        ),
    ]
