# Generated by Django 3.2.13 on 2022-04-18 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_loyalty', '0007_auto_20220418_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='created_up',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата добавления'),
            preserve_default=False,
        ),
    ]
