# Generated by Django 3.2.13 on 2022-04-18 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_loyalty', '0009_auto_20220418_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='finish_date',
            field=models.DateField(blank=True, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='дата начала'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(message='ИНН может содержать 10 или 12 цифр.', regex='^\\d{10,12}$')], verbose_name='ИНН'),
        ),
    ]
