# Generated by Django 3.2.13 on 2022-04-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_loyalty', '0010_auto_20220418_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='finish_date',
            field=models.DateField(blank=True, null=None, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_date',
            field=models.DateField(blank=True, null=None, verbose_name='дата начала'),
        ),
    ]
