# Generated by Django 3.2.13 on 2022-04-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_loyalty', '0011_auto_20220418_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='finish_date',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='start_date',
        ),
    ]
